### PR TITLE
DOC: Add License file.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add the `LICENSE` file to the repository.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@jhlegarreta  Do you have some documentation that the original authors want this LICENSE file applied?

It seems that this should be an upstream commit approved by the original team.

**Comment by jhlegarreta** [comment]
@hjmjohnson thanks for the review !

Due to the comment in [PR 8 upstream](https://github.com/Inria-Asclepios/SmoothingRecursiveYvvGaussianFilter/issues/8) I deduced that we should send our PRs to the ISC fork. Also I do submit them to the ISC fork because on the one hand at times we cannot be certain about the maintenance of the upstream fork; and on the other hand the `.remote.cmake` files in ITK usually draw from the ISC fork. But I would be fine if we knew beforehand that we should push upstream for some given repositories.

Finally, as for the license question, no I do not have upstream confirmation. But the Apache 2.0 license notice is written in the source headers, so I assume they are fine with this.

Else, we can ask directly @tvercaut  or @msermesant to comment on these aspects.

**Comment by tvercaut** [comment]
I confirm that Apache 2 is fine from our side. I am also in favour of making this fork the "official" one.

**Comment by jhlegarreta** [comment]
Thanks @tvercaut !

**Pull request merged**
