### PR TITLE
DOC: Follow repository naming convention.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Follow remote module repository naming convention: add the `ITK` prefix to
the **project name**, and keep the prefix out of the **module name**.

Specifically:
- Fix the **project name** in the `setup` section of the `setup.py` file.
- Change the **project name** in the `config.yml` Circle CI `yml` file.
- Take advantage of the change to set the URL to the repository site in
  `setup.py`.
- Take advantage of the change to add keywords describing the module to
  `setup.py`.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Looks like CI is not doing its job. The project is building/reporting in Circle CI at least so I do not see very well where the error is.

**Comment by thewtex** [comment]
@jhlegarreta side note: I enabled *Build forked pull requests* in the CircleCI settings so we get builds with pull requests:

image

**Review by thewtex — APPROVED** [review]
Thanks @jhlegarreta !

**Comment by jhlegarreta** [comment]
Thanks for the explanation Matt. I missed that when checking the settings.

**Pull request merged**
