### PR TITLE
Itk5threading

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
A simple test of test when built against TBB throws an error:
```
./SmoothingRecursiveYvvGaussianImageFilter mni_icbm152_nlin_sym_09b/mni_icbm152_t1_tal_nlin_sym_09b_hires.nii smooth3.nii.gz 18.81488772222677920916
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /storage/software/ANTs-build/ITKv5/Modules/Remote/SmoothingRecursiveYvvGaussianFilter/include/itkRecursiveLineYvvGaussianImageFilter.hxx:339:
itk::ERROR: RecursiveLineYvvGaussianImageFilter(0x55b57b9f8610): The number of pixels along direction 2 in this work-unit image region is less than 4. Note: TBBMultiThreader can divide small regions into really small pieces.
Aborted (core dumped
```

**Comment by gdevenyi** [comment]
Looks like the implementation might not handle DynamicThreads properly, changing to "platform" threading makes the bug go away

**Comment by gdevenyi** [comment]
Unfortunately the output is weirdly broken after switching to platform threading, looks like one dimenion has a weird stacking distortion

**Comment by dzenanz** [comment]
I reverted the switch to dynamic threading. Can you re-test now @gdevenyi?

**Comment by gdevenyi** [comment]
All fixed!

**Pull request merged**
